name: firebase_authentication
description: Dart package which manages the authentication domain.
version: 0.0.18
homepage: https://github.com/Flutter-libraries/firebase_authentication

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.1
  
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  freezed_annotation: ^2.0.3
  google_sign_in: ^6.0.1
  meta: ^1.3.0
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.1.2
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

scripts:
  build: "flutter pub run build_runner build --delete-conflicting-outputs"
  watch: "flutter pub run build_runner watch --delete-conflicting-outputs"