name: firebase_authentication
description: Dart package which manages the authentication domain.
version: 0.0.3
homepage: https://github.com/Flutter-libraries/firebase_authentication

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.3.4
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.3.2
  meta: ^1.3.0
  sign_in_with_apple: ^3.3.0
  very_good_analysis: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.2
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0
